functional:
  - требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - требование 2 Пользователь должен иметь возможность фильтровать товары.
  - требование 3 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - требование 4 Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - требование 5 Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - требование 6 Сайт должен быть безопасным и защищать данные пользователя.
  - требование 7 Сайт должен быть способен обрабатывать большое количество трафика.
  - требование 8 Сайт должен быть доступен на различных устройствах.
  - требование 9 Сайт должен иметь мобильную версию.
implicit:
  - требование 10 Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - требование 11 Сайт должен соответствовать действующему законодательству.
  
